version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor"]

  # - package-ecosystem: "pip"
  #   directory: "/src"
  #   schedule:
  #     interval: "weekly"
