# Generated by AI
import os
import sys

sys.path.append('../')
from anticorrupt import fetch_valid_image
from cloudflare import CloudflareR2
from system_utils import mkpath, posixpath

LIST_PATH = mkpath(os.path.dirname(__file__), 'corrupted_images.txt')
TEMP_DIR = mkpath(os.path.dirname(__file__), '_reupload_temp')


def load_list():
    if not os.path.isfile(LIST_PATH):
        print(f'List not found: {LIST_PATH}', file=sys.stderr)
        sys.exit(1)
    rows = []
    with open(LIST_PATH, encoding='utf-8') as f:
        header = f.readline().rstrip('\n').split('\t')
        idx = {name: i for i, name in enumerate(header)}
        required = {'country', 'lang', 'date', 'bing_url'}
        if not required.issubset(idx):
            print(f'List header missing required columns. Need {required}, got {header}', file=sys.stderr)
            sys.exit(1)
        for line in f:
            line = line.rstrip('\n')
            if not line:
                continue
            parts = line.split('\t')
            rows.append({
                'country': parts[idx['country']],
                'lang': parts[idx['lang']],
                'date': parts[idx['date']],
                'bing_url': parts[idx['bing_url']],
            })
    return rows


def main():
    rows = load_list()
    print(f'Loaded {len(rows)} corrupted entries from {LIST_PATH}')
    if not rows:
        return

    print('\nEntries to re-upload:')
    for row in rows:
        print(f'  {row["country"]}/{row["lang"]}/{row["date"]}')

    confirm = input('\nProceed with re-upload to R2? Type "yes" to continue: ').strip()
    if confirm != 'yes':
        print('Aborted.')
        return

    os.makedirs(TEMP_DIR, exist_ok=True)
    storage = CloudflareR2()

    ok = 0
    fail = 0
    for row in rows:
        country = row['country']
        lang = row['lang']
        date = row['date']
        bing_url = row['bing_url']
        key = posixpath(mkpath(country.upper(), lang.lower(), f'{date}.jpg'))
        print(f'\n=== {key} ===')
        print(f'  bing_url: {bing_url}')
        try:
            content = fetch_valid_image(bing_url)
        except Exception as exc:
            print(f'  FAILED to fetch: {exc}')
            fail += 1
            continue

        local_path = mkpath(TEMP_DIR, f'{country}_{lang}_{date}.jpg')
        with open(local_path, 'wb') as f:
            f.write(content)
        print(f'  fetched: {len(content)} bytes')

        try:
            storage.upload_file(local_path, key, skip_exists=False)
            ok += 1
        except Exception as exc:
            print(f'  FAILED to upload: {exc}')
            fail += 1
        finally:
            try:
                os.remove(local_path)
            except OSError:
                pass

    print(f'\nDone. OK: {ok}  FAIL: {fail}  / total: {len(rows)}')


if __name__ == '__main__':
    main()
