# Generated by AI
import os
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import NamedTuple

import requests

sys.path.append('../')
from anticorrupt import is_valid_image
from Region import REGIONS
from system_utils import mkpath

OUTPUT_PATH = mkpath(os.path.dirname(__file__), 'corrupted_images.txt')
MAX_WORKERS = 3
TIMEOUT = 30
USER_AGENT = 'Mozilla/5.0 (scan_corrupted_images.py)'


class Entry(NamedTuple):
    country: str
    lang: str
    date: str
    url: str
    bing_url: str


class CheckResult(NamedTuple):
    country: str
    lang: str
    date: str
    size: int
    reason: str


def collect_entries() -> list[Entry]:
    entries = []
    for region in REGIONS:
        for entry in region.read_api():
            if entry.bing_url and entry.url:
                entries.append(Entry(
                    country=region.api_country,
                    lang=region.api_lang,
                    date=entry.date.isoformat(),
                    url=entry.url,
                    bing_url=entry.bing_url,
                ))
    return entries


def check_entry(entry: Entry) -> CheckResult:
    base = {'country': entry.country, 'lang': entry.lang, 'date': entry.date}
    try:
        response = requests.get(entry.url, timeout=TIMEOUT, headers={'User-Agent': USER_AGENT})
        if response.status_code != 200:
            return CheckResult(**base, size=-1, reason=f'status={response.status_code}')
        ok, reason = is_valid_image(response.content)
        return CheckResult(**base, size=len(response.content), reason='ok' if ok else reason)
    except Exception as exc:
        return CheckResult(**base, size=-1, reason=f'error={exc}')


def fmt_mmss(seconds: float) -> str:
    s = int(seconds)
    return f'{s // 60}m{s % 60:02d}s'


def main():
    entries = collect_entries()
    total = len(entries)
    print(f'Scanning {total} archived images via public mirror...')

    bad = []
    done = 0
    start = time.monotonic()
    last_print = start
    last_progress_len = 0

    def emit_progress(now: float, final: bool = False):
        nonlocal last_progress_len
        elapsed = now - start
        rate = done / elapsed if elapsed > 0 else 0
        eta = (total - done) / rate if rate > 0 else 0
        pct = done * 100 / total
        line = (
            f'  progress: {done}/{total} ({pct:5.1f}%)  '
            f'bad={len(bad)}  rate={rate:.1f}/s  '
            f'elapsed={fmt_mmss(elapsed)}  eta={fmt_mmss(eta)}'
        )
        pad = ' ' * max(0, last_progress_len - len(line))
        end = '\n' if final else ''
        print(f'\r{line}{pad}', end=end, flush=True)
        last_progress_len = len(line)

    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as pool:
        futures = [pool.submit(check_entry, entry) for entry in entries]
        for future in as_completed(futures):
            result = future.result()
            done += 1
            if result.reason != 'ok':
                bad.append(result)
                pad = ' ' * last_progress_len
                print(
                    f'\r{pad}\r  BAD: {result.country}/{result.lang}/{result.date}  '
                    f'size={result.size}  reason={result.reason}',
                    flush=True
                )
                last_progress_len = 0

            now = time.monotonic()
            if done == total or now - last_print >= 1.0:
                emit_progress(now, final=(done == total))
                last_print = now

    bad.sort()
    print(f'\nTotal corrupted: {len(bad)}')

    bing_url_by_key = {(entry.country, entry.lang, entry.date): entry.bing_url for entry in entries}

    with open(OUTPUT_PATH, 'w', encoding='utf-8', newline='\n') as f:
        f.write('country\tlang\tdate\tsize\treason\tbing_url\n')
        for result in bad:
            bing_url = bing_url_by_key[(result.country, result.lang, result.date)]
            f.write(f'{result.country}\t{result.lang}\t{result.date}\t{result.size}\t{result.reason}\t{bing_url}\n')

    print(f'List written to: {OUTPUT_PATH}')


if __name__ == '__main__':
    main()
