exclude:
  - "/src/cache/"
  - "/src/checks/"
  - "/src/exiftool/"
  - "/src/old/"
  - "/src/requirements/"
  - "/src/sources/"
  - "/src/videos/"
  # --------------------
  - "/CHNAME"
  - "/LICENSE"
  - "/README.md"
  # --------------------
  - ".*"
  - "*.py"
  - "*.cmd"
  - "*.jsx"
