# Generated by AI
import time
from io import BytesIO

import requests
from PIL import Image

from system_utils import warn

MIN_IMAGE_BYTES = 200_000  # 0.2 MB
MIN_IMAGE_WIDTH = 1920
DOWNLOAD_ATTEMPTS = 4
DOWNLOAD_RETRY_SLEEP = 60
REQUEST_TIMEOUT = 60


def is_valid_image(content: bytes) -> tuple[bool, str]:
    if len(content) < MIN_IMAGE_BYTES:
        return False, f'too small: {len(content)} bytes (<{MIN_IMAGE_BYTES})'
    try:
        with Image.open(BytesIO(content)) as img:
            width, _ = img.size
    except Exception as exc:
        return False, f'decode failed: {exc}'
    if width < MIN_IMAGE_WIDTH:
        return False, f'too narrow: {width}px (<{MIN_IMAGE_WIDTH})'
    return True, 'ok'


def fetch_valid_image(
    bing_url: str, attempts: int = DOWNLOAD_ATTEMPTS, retry_sleep: float = DOWNLOAD_RETRY_SLEEP
) -> bytes:
    last_err = ''
    for attempt in range(1, attempts + 1):
        try:
            r = requests.get(bing_url, timeout=REQUEST_TIMEOUT)
            r.raise_for_status()
            content = r.content
        except Exception as exc:
            last_err = f'request failed: {exc}'
            warn(f'fetch_valid_image: {bing_url} (attempt {attempt}/{attempts}): {last_err}')
            if attempt < attempts:
                time.sleep(retry_sleep)
            continue

        ok, reason = is_valid_image(content)
        if ok:
            return content

        last_err = reason
        warn(f'fetch_valid_image: bad response for {bing_url} (attempt {attempt}/{attempts}): {last_err}')
        if attempt < attempts:
            time.sleep(retry_sleep)

    raise RuntimeError(f'fetch_valid_image: gave up on {bing_url} after {attempts} attempts: {last_err}')
