# Generated by AI
"""
Compare images across languages within the same country to determine whether
storing per-language images for the same region is meaningful.

Currently only Canada has multiple languages (en, fr) among the tracked regions.
The script downloads both versions of every shared date and compares SHA-256
hashes of the raw bytes (Bing CDN source).

CDN noise handling: Bing CDN is non-deterministic — different edges can serve
different re-encoded versions of the same source image (byte-different but
visually identical). When a date appears "different" on first pass, the script
re-fetches with `cache-bust` and retries. It also performs a perceptual check
(downscaled mean absolute pixel diff) to classify "near-identical" vs "truly
different" content.

Outputs a summary table and a CSV with per-date results.
"""
from __future__ import annotations

import csv
import hashlib
import os
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from io import BytesIO
from typing import Iterable

import requests
from PIL import Image

sys.path.append('../../')
from Region import REGIONS
from structures import ApiEntry
from system_utils import mkpath

CACHE_DIR = mkpath(os.path.dirname(__file__), '.cache', 'multilang_images')
OUTPUT_CSV = mkpath(os.path.dirname(__file__), 'multilang_image_diff.csv')

MAX_WORKERS = 16
REQUEST_TIMEOUT = 60
USER_AGENT = 'Mozilla/5.0 (compare_multilang_images.py)'

CDN_RETRIES = 2
PERCEPTUAL_THRESHOLD = 8.0


@dataclass
class ImageRef:
    region_id: str
    country: str
    lang: str
    date: str
    bing_url: str

    @property
    def cache_path(self) -> str:
        return mkpath(CACHE_DIR, self.country, self.lang, f'{self.date}.bin')


def group_regions_by_country() -> dict[str, list]:
    groups: dict[str, list] = {}
    for region in REGIONS:
        groups.setdefault(region.api_country, []).append(region)
    return {c: regs for c, regs in groups.items() if len(regs) > 1}


def download(
    ref: ImageRef, session: requests.Session, force: bool = False
) -> tuple[ImageRef, bytes | None, str | None]:
    if not force and os.path.isfile(ref.cache_path) and os.path.getsize(ref.cache_path) > 0:
        with open(ref.cache_path, 'rb') as f:
            return ref, f.read(), None

    try:
        r = session.get(ref.bing_url, timeout=REQUEST_TIMEOUT, headers={'User-Agent': USER_AGENT})
        r.raise_for_status()
        content = r.content
    except Exception as exc:
        return ref, None, str(exc)

    os.makedirs(os.path.dirname(ref.cache_path), exist_ok=True)
    with open(ref.cache_path, 'wb') as f:
        f.write(content)
    return ref, content, None


def perceptual_diff(a: bytes, b: bytes) -> float | None:
    """Return mean absolute RGB diff after 256x256 downscale. None on decode error."""
    try:
        import numpy as np
        with Image.open(BytesIO(a)) as ia, Image.open(BytesIO(b)) as ib:
            ia = ia.convert('RGB').resize((256, 256), Image.Resampling.LANCZOS)
            ib = ib.convert('RGB').resize((256, 256), Image.Resampling.LANCZOS)
            arr_a = np.asarray(ia, dtype=np.int16)
            arr_b = np.asarray(ib, dtype=np.int16)
            return float(np.abs(arr_a - arr_b).mean())
    except Exception:
        return None


def collect_refs(
    country: str, regions: Iterable
) -> tuple[dict[str, dict[str, ImageRef]], dict[str, dict[str, ApiEntry]]]:
    """Return {date: {lang: ImageRef}} restricted to dates present in ALL langs."""
    per_lang: dict[str, dict[str, ApiEntry]] = {}
    for region in regions:
        api_entries = region.read_api()
        per_lang[region.api_lang] = {entry.date.isoformat(): entry for entry in api_entries if entry.bing_url}

    common_dates = set.intersection(*(set(d.keys()) for d in per_lang.values()))
    result: dict[str, dict[str, ImageRef]] = {}
    for date in sorted(common_dates):
        result[date] = {}
        for lang, by_date in per_lang.items():
            entry = by_date[date]
            assert entry.bing_url is not None
            result[date][lang] = ImageRef(
                region_id=f'{country}-{lang}',
                country=country,
                lang=lang,
                date=date,
                bing_url=entry.bing_url,
            )
    return result, per_lang


def compare_country(country: str, regions: list) -> None:
    print(f'\n=== Comparing region {country} across langs: {[r.api_lang for r in regions]} ===')
    refs_by_date, _ = collect_refs(country, regions)
    if not refs_by_date:
        print('No common dates found.')
        return

    print(f'Common dates: {len(refs_by_date)}')

    all_refs: list[ImageRef] = [ref for langs in refs_by_date.values() for ref in langs.values()]

    session = requests.Session()
    contents: dict[tuple[str, str], bytes] = {}
    errors: list[tuple[ImageRef, str]] = []

    print(f'Downloading {len(all_refs)} images (cache: {CACHE_DIR})...')
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as pool:
        futures = [pool.submit(download, ref, session) for ref in all_refs]
        done = 0
        for fut in as_completed(futures):
            ref, content, err = fut.result()
            done += 1
            if err is not None or content is None:
                errors.append((ref, err or 'empty'))
            else:
                contents[(ref.date, ref.lang)] = content
            if done % 50 == 0 or done == len(all_refs):
                print(f'  {done}/{len(all_refs)}')

    if errors:
        print(f'\n{len(errors)} download errors (showing first 5):')
        for ref, err in errors[:5]:
            print(f'  {ref.region_id} {ref.date}: {err}')

    rows = []
    bytes_equal_n = 0
    near_identical_n = 0
    different_n = 0
    missing_n = 0

    langs_sorted = sorted({r.api_lang for r in regions})
    base_lang = langs_sorted[0]
    other_langs = langs_sorted[1:]

    def classify_pair(base_b: bytes, other_b: bytes, ref_other: ImageRef) -> tuple[str, float | None]:
        base_h = hashlib.sha256(base_b).hexdigest()
        other_h = hashlib.sha256(other_b).hexdigest()
        if base_h == other_h:
            return 'bytes_equal', 0.0

        for _ in range(CDN_RETRIES):
            _, fresh, err = download(ref_other, session, force=True)
            if err or fresh is None:
                break
            if hashlib.sha256(fresh).hexdigest() == base_h:
                with open(ref_other.cache_path, 'wb') as f:
                    f.write(fresh)
                return 'bytes_equal_after_retry', 0.0
            other_b = fresh

        pd = perceptual_diff(base_b, other_b)
        if pd is None:
            return 'undecodable', None
        if pd <= PERCEPTUAL_THRESHOLD:
            return 'near_identical', pd
        return 'different', pd

    for date, lang_refs in refs_by_date.items():
        base_bytes = contents.get((date, base_lang))
        if base_bytes is None:
            missing_n += 1
            rows.append({'date': date, 'status': 'missing_base', 'detail': base_lang})
            continue

        date_status = 'bytes_equal'
        details: list[str] = []

        for lang in other_langs:
            other_bytes = contents.get((date, lang))
            if other_bytes is None:
                date_status = 'missing'
                details.append(f'{lang}=missing')
                continue
            status, pd = classify_pair(base_bytes, other_bytes, lang_refs[lang])
            pd_str = '' if pd is None else f'(pd={pd:.2f})'
            details.append(f'{lang}={status}{pd_str}')

            rank = {
                'bytes_equal': 0,
                'bytes_equal_after_retry': 1,
                'near_identical': 2,
                'different': 3,
                'undecodable': 4,
                'missing': 4,
            }
            if rank.get(status, 0) > rank.get(date_status, 0):
                date_status = status

        if date_status in ('bytes_equal', 'bytes_equal_after_retry'):
            bytes_equal_n += 1
        elif date_status == 'near_identical':
            near_identical_n += 1
        elif date_status == 'different':
            different_n += 1
        else:
            missing_n += 1

        rows.append({'date': date, 'status': date_status, 'detail': ';'.join(details)})

    total = len(refs_by_date)
    print(f'\n--- Results for {country} ---')
    print(f'Total compared dates: {total}')
    print(f'  bytes-identical   : {bytes_equal_n} ({bytes_equal_n / total:.1%})')
    print(f'  near-identical*   : {near_identical_n} ({near_identical_n / total:.1%})')
    print(f'  visually different: {different_n} ({different_n / total:.1%})')
    print(f'  missing/error     : {missing_n} ({missing_n / total:.1%})')
    print(f'  * mean abs RGB diff <= {PERCEPTUAL_THRESHOLD} after 256x256 downscale')

    with open(OUTPUT_CSV, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=['country', 'date', 'status', 'detail'])
        writer.writeheader()
        for row in rows:
            writer.writerow({'country': country, **row})

    print(f'\nPer-date CSV: {OUTPUT_CSV}')


def main() -> None:
    multi = group_regions_by_country()
    if not multi:
        print('No countries with multiple languages found.')
        return

    print(f'Countries with multiple languages: {list(multi.keys())}')
    for country, regions in multi.items():
        compare_country(country, regions)


if __name__ == '__main__':
    main()
