:: File generated by AI

@echo off
setlocal enabledelayedexpansion

:: --- Configuration ---
set "SCRIPT_NAME=squash_archive.sh"
set "SCRIPT_PATH=%~dp0%SCRIPT_NAME%"

:: --- Find Git Bash (sh.exe) ---
set "GITSHELL="

:: 1. Try standard installation paths
for %%P in (
    "C:\Program Files\Git\bin\sh.exe"
    "C:\Program Files (x86)\Git\bin\sh.exe"
    "%USERPROFILE%\AppData\Local\Programs\Git\bin\sh.exe"
) do (
    if exist "%%~P" (
        set "GITSHELL=%%~P"
        goto :found
    )
)

:: 2. Try to find in PATH
where sh.exe >nul 2>&1
if %errorlevel% == 0 (
    for /f "delims=" %%I in ('where sh.exe') do (
        set "GITSHELL=%%I"
        goto :found
    )
)

:found
if "%GITSHELL%"=="" (
    echo [ERROR] Git Bash (sh.exe) not found.
    echo Please install Git for Windows or ensure sh.exe is in your PATH.
    pause
    exit /b 1
)

:: --- Run the Script ---
echo [INFO] Environment: Windows
echo [INFO] Shell: %GITSHELL%
echo [INFO] Running: %SCRIPT_NAME%...
echo.

:: Convert backslashes to forward slashes for Bash
set "BASH_PATH=%SCRIPT_PATH:\=/%"

:: Execute
"%GITSHELL%" --login -c "'%BASH_PATH%'"

if %errorlevel% neq 0 (
    echo.
    echo [ERROR] Script execution failed with exit code %errorlevel%
    pause
    exit /b %errorlevel%
)

echo.
echo [SUCCESS] Operation completed.
pause
exit /b 0
