name: Metadata check

on: push

jobs:
  check_metadata:
    runs-on: [ubuntu-latest]
    steps:

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install Python's requirements
        run: pip install -r requirements.txt

      - name: Download exiftool
        run: |
          wget https://npanuhin.me/files/Image-ExifTool-12.37.tar.gz
          gzip -dc Image-ExifTool-12.37.tar.gz | tar -xf -
          chmod -R 777 Image-ExifTool-12.37
          cd Image-ExifTool-12.37
          perl Makefile.PL
          make test
          sudo make install

      - name: Check metadata
        working-directory: src/checks
        run: python check_metadata.py
