name: Broken images check

on:
  push:
  workflow_dispatch:

jobs:
  check-broken-images:
    name: Check broken images
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install Python's requirements
        run: pip install -r src/requirements/check_broken_images.txt

      - name: Check broken images
        working-directory: src/checks
        run: python check_broken_images.py
