name: Metadata check

on:
  push:
  workflow_dispatch:

jobs:
  check-metadata:
    name: Check metadata
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install Python's requirements
        run: pip install -r src/requirements/check_metadata.txt

      - name: Download & Install ExifTool
        working-directory: src/exiftool
        run: |
          wget https://npanuhin.me/files/Image-ExifTool-12.38.tar.gz
          gzip -dc Image-ExifTool-12.38.tar.gz | tar -xf - --strip-components=1

      - name: Check metadata
        working-directory: src/checks
        run: python check_metadata.py
