name: Daily update

on:
  schedule:
    - cron: "50 23 * * *"

jobs:
  update_images:
    runs-on: [ubuntu-latest]
    steps:

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install Python's requirements
        run: pip install -r requirements.txt

      - name: Download & install ExifTool
        run: |
          cd ..
          wget https://npanuhin.me/files/Image-ExifTool-12.37.tar.gz
          gzip -dc Image-ExifTool-12.37.tar.gz | tar -xf -
          chmod -R 777 Image-ExifTool-12.37
          cd Image-ExifTool-12.37
          perl Makefile.PL
          make test
          sudo make install

      - name: Daily update
        working-directory: src
        run: python daily_update.py

      # - name: GPG
      #   uses: crazy-max/ghaction-import-gpg@v4
      #   with:
      #     gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.PASSPHRASE }}
      #     git_user_signingkey: true
      #     git_commit_gpgsign: true
      #     # git_tag_gpgsign: true

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Images update: US to ${{ steps.date.outputs.date }}"
          # commit_options: '-S'
          commit_author: GitHub Actions <actions@github.com>
