name: Daily update

on:
  schedule:
    - cron: '2 8 * * *'  # 8:02 UTC
  workflow_dispatch:

permissions: {}  # Using PAT

concurrency:
  group: "daily_update"
  cancel-in-progress: false

jobs:
  update-images:
    name: Update images
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip

      - name: Install Python's requirements
        working-directory: src
        run: pip install -r requirements.txt

      - name: Update archive
        working-directory: src
        run: python update.py
        env:
          CLOUDFLARE_ACCOUNT_ID: '${{ secrets.CLOUDFLARE_ACCOUNT_ID }}'
          CLOUDFLARE_AWS_ACCESS_KEY_ID: '${{ secrets.CLOUDFLARE_AWS_ACCESS_KEY_ID }}'
          CLOUDFLARE_AWS_SECRET_ACCESS_KEY: '${{ secrets.CLOUDFLARE_AWS_SECRET_ACCESS_KEY }}'

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Archive update"
          commit_user_name: GitHub Actions
          commit_author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
