name: Daily update

on:
  schedule:
    - cron: '50 23 * * *'
  workflow_dispatch:

concurrency:
  group: "all"
  cancel-in-progress: false

jobs:
  update-images:
    name: Update images
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
          cache: pip

      - name: Install Python's requirements
        working-directory: src
        run: pip install -r requirements.txt

      - name: Google Cloud Authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCLOUD_CREDENTIALS }}'

      - name: Update archive
        working-directory: src
        run: python update.py

      - name: Remove GCloud credentials
        run: rm -f $GOOGLE_GHA_CREDS_PATH

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Archive update"
          commit_user_name: GitHub Actions
          # commit_author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
