name: Daily update

on:
  schedule:
    - cron: "50 23 * * *"
  workflow_dispatch:

jobs:
  update-images:
    name: Update images
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install Python's requirements
        run: pip install -r src/requirements/daily_update.txt

      - name: Download & Install ExifTool
        working-directory: src/exiftool
        run: |
          wget https://npanuhin.me/files/Image-ExifTool-12.38.tar.gz
          gzip -dc Image-ExifTool-12.38.tar.gz | tar -xf - --strip-components=1

      - name: Daily update
        working-directory: src
        run: python daily_update.py

      # - name: GPG
      #   uses: crazy-max/ghaction-import-gpg@v4
      #   with:
      #     gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.PASSPHRASE }}
      #     git_user_signingkey: true
      #     git_commit_gpgsign: true
      #     # git_tag_gpgsign: true

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Images update: US to ${{ steps.date.outputs.date }}"
          # commit_options: '-S'
          commit_user_name: GitHub Actions
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
