name: Daily update

on:
  schedule:
    - cron: '50 23 * * *'
  workflow_dispatch:


jobs:
  update-images:
    name: Update images
    runs-on: ubuntu-latest

    steps:
      # - name: Clone repository
      #   uses: actions/checkout@v3
      #   with:
      #     token: ${{ secrets.PAT }}
      #     ssh-key: ${{ secrets.SSH_KEY }}

      - name: Fetch repository info
        id: repository
        run: |
          echo "::set-output name=name::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"
          echo "::set-output name=url::$(echo https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git)"

      - name: Partially clone repository
        run: |
          git clone --depth 1 --filter=blob:none --sparse ${{ steps.repository.outputs.url }}
          cd ${{ steps.repository.outputs.name }}
          git sparse-checkout set --no-cone "*" "!*.jpg" "!*.mp4"

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip
          cache-dependency-path: ${{ steps.repository.outputs.name }}/src/requirements/daily_update.txt

      - name: Install Python's requirements
        working-directory: ${{ steps.repository.outputs.name }}/src/requirements
        run: pip install -r daily_update.txt

      - name: Check for ExifTool in cache
        id: exiftool-cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.repository.outputs.name }}/src/exiftool
          key: ExifTool-${{ runner.os }}

      - name: Download ExifTool
        if: steps.exiftool-cache.outputs.cache-hit != 'true'
        working-directory: ${{ steps.repository.outputs.name }}/src/exiftool
        run: |
          wget https://npanuhin.me/files/Image-ExifTool-12.38.tar.gz
          gzip -dc Image-ExifTool-12.38.tar.gz | tar -xf - --strip-components=1
          rm -f Image-ExifTool-12.38.tar.gz

      - name: Update images
        working-directory: ${{ steps.repository.outputs.name }}/src
        run: python update.py

      # - name: GPG
      #   uses: crazy-max/ghaction-import-gpg@v4
      #   with:
      #     gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.PASSPHRASE }}
      #     git_user_signingkey: true
      #     git_commit_gpgsign: true
      #     # git_tag_gpgsign: true

      - name: Fetch current date
        run: echo "date=yellow" >> $GITHUB_ENV

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: ${{ steps.repository.outputs.name }}
          commit_message: "Archive update: US to ${{ env.date }}"
          add_options: --sparse
          commit_user_name: GitHub Actions
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
