name: Daily update

on:
  schedule:
    - cron: "50 23 * * *"

jobs:
  update_images:
    runs-on: [ubuntu-latest]
    steps:

      - name: Clone repository
        uses: actions/checkout@master
        with:
          token: ${{ secrets.PAT }}

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install Python's requirements
        run: pip install -r requirements.txt

      - name: Download exiftool
        run: |
          cd ..
          wget https://npanuhin.me/files/Image-ExifTool-12.37.tar.gz
          gzip -dc Image-ExifTool-12.37.tar.gz | tar -xf -
          chmod -R 777 Image-ExifTool-12.37
          cd Image-ExifTool-12.37
          perl Makefile.PL
          make test
          sudo make install

      - name: Daily update
        working-directory: src
        run: python daily_update.py

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Images update: US to ${{ steps.date.outputs.date }}"
          commit_author: GitHub Actions <actions@github.com>
