name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
    # paths:
    #   - src/website/**
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          # No pip cache, since no modules are installed

      - name: Generate website
        working-directory: src/scripts
        run: python assemble_website.py

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'src/website'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
