name: Website build & deployment

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "website"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    name: Build & deploy website
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - name: Cache Python dependencies
        uses: actions/cache@v5
        id: cache-python
        with:
          path: src/venv
          key: ${{ runner.os }}-venv-${{ hashFiles('src/requirements.txt') }}

      - name: Install Python dependencies
        if: steps.cache-python.outputs.cache-hit != 'true'
        working-directory: src
        run: |
          python -m venv venv
          venv/bin/pip install -r requirements.txt

      - name: Add Python venv to PATH
        working-directory: src
        run: echo "${GITHUB_WORKSPACE}/src/venv/bin" >> "$GITHUB_PATH"

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Cache Node.js dependencies
        uses: actions/cache@v5
        id: cache-node
        with:
          path: src/website/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('src/website/package-lock.json') }}

      - name: Install Node.js dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        working-directory: src/website
        run: npm ci

      # ----------------------------------------------------------------------------------------------------------------

      - name: Build website
        working-directory: src/website
        run: npm run build

      - name: Deploy website
        working-directory: src/website
        run: npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_WORKERS_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      # ----------------------------------------------------------------------------------------------------------------

      - name: Update README
        working-directory: src
        run: python update_readme.py
        env:
          CLOUDFLARE_ACCOUNT_ID: '${{ secrets.CLOUDFLARE_ACCOUNT_ID }}'
          CLOUDFLARE_R2_ACCESS_KEY_ID: '${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}'
          CLOUDFLARE_R2_API_TOKEN: '${{ secrets.CLOUDFLARE_R2_API_TOKEN }}'

      - name: Commit and push changes
        if: ${{ steps.previous_commit.outputs.PREVIOUS_COMMIT_AUHOUR != 'GitHub Actions' }}
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: README update
          commit_user_name: GitHub Actions
          commit_author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
          file_pattern: 'README.md'
